### ISSUE TITLE
Failed test 'event results is 110 (2019-2020)'

### ISSUE THREAD

**Issue by eserte** [kan/p5-web-service-mailgun#1]
The test suite started to fail since some days, see http://matrix.cpantesters.org/?dist=WebService-Mailgun%200.07;reports=1#sl=7,1

Excerpt of test log:
```
    #   Failed test 'event results is 110 (2019-2020)'
    #   at t/04_event.t line 23.
    #          got: '0'
    #     expected: '110'
    # Looks like you failed 1 test of 2.

#   Failed test 'get events'
#   at t/04_event.t line 25.
# Looks like you failed 1 test of 1.
t/04_event.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by joshrabinowitz** [comment]
I'm seeing this on all my linux boxes, too

**Comment by kan** [comment]
@eserte @joshrabinowitz Thank you for your report.

@joshrabinowitz Thank you pull-request. I merged your PR. And release 0.08.
