### ISSUE TITLE
API URL for EU

### ISSUE THREAD

**Issue by bjornjac** [kan/p5-web-service-mailgun#10]
$API_BASE is hardcoded to the US (non-EU) API URL.

The API URL is different for domains registered as EU (required due to different privacy regulation, GDPR) and need to be api.eu.mailgun.net/v3

Is it possible to add a "eu" flag to the constructor, or maybe a more general "region" attribute and default it to the US one? Can possibly make API_BASE overridable but that seems like a bad idea maintenance wise from the outside world.

If you want, I can modify the code and send the patch.

**Comment by bjornjac** [comment]
Here is the patch I'm using, but you may prefer some other style/solution. Since the change is minor, I didn't bother to fork the repo

--- Mailgun.pm  2022-01-16 12:04:00.116586000 +0000
+++ /usr/local/lib/perl5/site_perl/WebService/Mailgun.pm        2022-01-16 12:15:41.993189000 +0000
@@ -16,10 +16,11 @@
 
 our $VERSION = "0.13";
 our $API_BASE = 'api.mailgun.net/v3';
+our $API_BASE_EU = 'api.eu.mailgun.net/v3';
 
 use Class::Accessor::Lite (
     new => 1,
-    rw  => [qw(api_key domain RaiseError)],
+    rw  => [qw(api_key domain RaiseError region)],
     ro  => [qw(error error_status)],
 );
 
@@ -84,18 +85,31 @@
     );
 }
 
+sub api_base {
+    my ($self) = @_;
+
+    if ($self->region) {
+        if ($self->region eq "eu") {
+            return $API_BASE_EU;
+        } elsif ($self->region ne "us") {
+            die "unsupported region '" . $self->region ."'";
+        }
+    }
+    return $API_BASE;
+}
+
 sub api_url {
     my ($self, $method) = @_;

     sprintf 'https://api:%s@%s/%s',
-        $self->api_key, $API_BASE, $method;
+        $self->api_key, $self->api_base, $method;
 }
 
 sub domain_api_url {
     my ($self, $method) = @_;
 
     sprintf 'https://api:%s@%s/%s/%s',
-        $self->api_key, $API_BASE, $self->domain, $method;
+        $self->api_key, $self->api_base, $self->domain, $method;
 }
 
 sub message {

**Comment by bjornjac** [comment]
Here is the patch I'm using myself, if you want to use it:

[patch.txt](https://github.com/kan/p5-web-service-mailgun/files/7876916/patch.txt.txt)

**Comment by kan** [comment]
@bjornjac 
Thanks for the suggestion and the patch. Could you please submit this fix as a pull-request?

**Comment by bjornjac** [comment]
I cloned the repo and added a pull request for the changes. Feel free to edit for style or whatever you want. Since there are only two regions, I just did it the simple way.

**Comment by kan** [comment]
Thank you for your  pull-request. I merged it, and ship 0.14 .
Please wait for it to be published on CPAN.
