### ISSUE TITLE
Failing non-ascii characters on "message" method

### ISSUE THREAD

**Issue by bjornjac** [kan/p5-web-service-mailgun#13]
When posting data using the message method, non-ascii characters passed as arguments comes through garbled in messages sent from Mailgun.

When not setting content type to "form-data" (using default), it comes through fine with iso-8859-1 characters. The data is then sent as application/x-www-form-urlencoded (URL paramter string) rather than multipart/form-data (mime chunks).

I have tried most things, like encoding/decoding the arguments, but they always comes out garbled in the mails from Mailgun unless I convert the arguments to 8 bit characters first (not really a fix for those needing wider characters). I don't really know if the problem is on Mailguns side (not handling utf-8 in form-data possibly?) or HTTP::Request/Furl does something weird (the content it generates seems accurate, but with form-data there is no charset passed so it might just assume it's 8 bit latin 1).

I didn't open a pull request because I don't know how it will work with non-8-bit character sets.

**Comment by kan** [comment]
I don't know the details of what encode/decode you have tried, but I assume the message method is passed a decoded internal string.
If you write the string in code, specify "use utf8". If you are reading from a file, etc., use decode_utf8, etc.

**Comment by bjornjac** [comment]
The argument hash contains utf-8 data and various combinations of 'use utf8', 'use v5.32' and such doesn't change the problem. Forcing the arguments to latin-1 (decode utf8, encode latin-1) works, but if the arguments are 8 bits anyway and MG doesn't support utf-8, then just using URL-encoding works fine without having to worry about input character set.

Just to clarify. I do send the messages using templates on the MG side so the arguments are expanded as 8-bit and utf-8 comes out garbled. Which means, MG does something to them since it would be fine if it was raw/binary data. The template itself comes back fine with utf-8, just not the substituted variables from 'message' arguments.

I assume the problem is on MGs side though, but I haven't received an answer from them on the issue.

**Comment by kan** [comment]
Sorry, I have never encountered a similar problem so I don't know what to do.

> Forcing the arguments to latin-1 (decode utf8, encode latin-1) works

In the meantime, what happens if I pass the message to message without encode?

I'm going to close this issue because I don't know how to deal with it any further. Please let me know if you get any response from mailgun.
