### ISSUE TITLE
[Perl advocacy] get this module listed in Mailgun's client example code

### ISSUE THREAD

**Issue by oodler577** [kan/p5-web-service-mailgun#4]
This module is pretty rad, because of it I am considering using MG for a client of mine. But I noticed that it's not listed in the "Quck Start" doc.

https://documentation.mailgun.com/en/latest/quickstart.html

**Comment by kan** [comment]
Thank you for using this module. I too would like to see a description of this module on that page, but I don't know how to do it.
If you know how to get it listed, please let me know.
