### ISSUE TITLE
Sending MIME messages

### ISSUE THREAD

**Issue by justingit** [kan/p5-web-service-mailgun#5]
Are you at all considering adding support for sending raw MIME messages? If not, would you accept a PR?

**Comment by kan** [comment]
I think that feature is necessary, but we had no plans to implement it at this time.
If you can send me a PR, I'd welcome it.

**Comment by kan** [comment]
@justingit 
Thanks for the PR.
I've released 0.12 with your fix, please wait for it to be reflected in CPAN. I apologize for the delay in response.
