### ISSUE TITLE
Using JSON::XS rather than just, JSON

### ISSUE THREAD

**Issue by justingit** [kan/p5-web-service-mailgun#8]
Is there a reason that the JSON::XS module is explicitly used, rather than JSON? For slightly better portability, would simply using, JSON be preferable? JSON will use JSON::XS if it is available, before falling back to a Pure Perl module, or can be configiured to allow you to choose.

**Comment by kan** [comment]
@justingit 
I think it is a very good suggestion.
If you've already created a pull-request, could you send it to me?

**Comment by justingit** [comment]
Here's the PR for you: https://github.com/kan/p5-web-service-mailgun/pull/9

**Comment by kan** [comment]
Thanks your PR.
I merged it, and release 0.13 !

**Comment by justingit** [comment]
Cool! I may have a bigger ask, but I can provide a PR for it. I'll open up a new issue, soonish.
